# PyTorch Sequence Batch Loading
### By Noah Ziems

As it turns out, RNNs tend to be really slow to train. This is mainly because they are tough to train in batches. You can only run one input at a time through the network. Its worth noting this is one of the big reasons Transformer-based architectures have performed so well compared to traditional sequence-based models. Thankfully, PyTorch has a bunch of built-in methods to help speed up training RNNs. In this notebook, we'll explore a few of those.

First let's start off importing everything we need.

In [1]:
import torch
from torch import nn
from torch import optim
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pad_sequence, pack_padded_sequence, pad_packed_sequence
from torch.nn import functional as F

### Quotes

Lets keep things really really simple for now. We're going to make a datset with only 3 data points! Each quote(split by chars) will be the input and the goal of the RNN will simply be to recognize the quote.

In [2]:
q1 = "Well done is better than well said".lower()
q2 = "Better slip with foot than tongue".lower()
q3 = "There never was a good war or a bad peace".lower()
quotes = [q1, q2, q3]
quotes

['well done is better than well said',
 'better slip with foot than tongue',
 'there never was a good war or a bad peace']

### Sources
Here are the sources of our quotes. Nothing much to say here.

In [3]:
s1 = 0
s2 = 1
s3 = 2
sources = [s1, s2, s3]
sources

[0, 1, 2]

### Tokenization
Alright heres where things get interesting. We're breaking our dataset into tokens that can be fed into our RNN.

First we reserve some tokens like `<pad>`(padding), `<eos>`(end of sentence), `<unk>`(unknown). These are used to indicate to the RNN some things that may not be properly extracted from the regular tokens.

Next, we join all the quotes together and create a set of chars out of them. A set simply means a collection with no repeating elements(we dont want the same character to have two different tokens).

Lastly, we print them out as a sanity check to make sure everything looks right.

In [4]:
chars = ['<pad>', '<eos>', '<unk>'] + list(set(' '.join(quotes)))
nb_char = len(chars)

print(f'There are {nb_char} unique characters')
chars

There are 23 unique characters


['<pad>',
 '<eos>',
 '<unk>',
 'l',
 'i',
 's',
 'd',
 'n',
 'g',
 't',
 'v',
 'f',
 'h',
 'e',
 'u',
 'c',
 'p',
 'o',
 'w',
 'r',
 ' ',
 'a',
 'b']

### Conversion Dictionaries
To make sure we can easily convert `chars` -> `ids` and `ids` to `chars`, we create two different dictionaries. These are really useful for encoding any given sentence before its given to the RNN and decoding any sentence. In this notebook we don't decode any sentences, but its still a good habit to put this in here.

Once again, lets print some things out so we can make sure everything looks right.

In [5]:
char_to_ix = { ch:i for i,ch in enumerate(chars)}
ix_to_char = { i:ch for i,ch in enumerate(chars)}

char_to_ix

{'<pad>': 0,
 '<eos>': 1,
 '<unk>': 2,
 'l': 3,
 'i': 4,
 's': 5,
 'd': 6,
 'n': 7,
 'g': 8,
 't': 9,
 'v': 10,
 'f': 11,
 'h': 12,
 'e': 13,
 'u': 14,
 'c': 15,
 'p': 16,
 'o': 17,
 'w': 18,
 'r': 19,
 ' ': 20,
 'a': 21,
 'b': 22}

### Creating Tensor Sequences
Let's tokenize each of our quotes by converting each character into its corresponding id then putting all those ids into a pytorch vector. Lastly, we put each of those vectors in a list.
 Notice how the size of each tensor is the exact same as the length of each quote.

In [6]:
x_seq = [torch.tensor(list(map(lambda char: char_to_ix[char], i))) for i in quotes]
[x.shape for x in x_seq]

[torch.Size([34]), torch.Size([33]), torch.Size([41])]

### Padding Our Sequences
When we send our batches to the GPU, they have to be sent as a single tensor. This means each quote has to be the same length when they get sent to the GPU. Unfortunately, not all our quotes are the same length. One is 34 chars, one is 33, and the last is 41. Therefore we have to pad each quote so they are all the same length. Thankfully, PyTorch has a function for this called `pad_sequence`.

To use `pad_sequence` we simply give it our list of tokenized sequences from the last cell, tell it to pad after each sentence(instead of before), and tell it which value to pad with(in this case, our `<pad>` token.

Now you can see that all of our padded sequences are the same length(the length of the longest quote). Time to move on!

In [7]:
x_padded = pad_sequence(x_seq, batch_first=True, padding_value=char_to_ix['<pad>'])
[x.shape for x in x_padded]

[torch.Size([41]), torch.Size([41]), torch.Size([41])]

### Create the Dataset

Let's create a quick dataset so we can use the PyTorch Dataloader. I won't go over this in too much detail. Notice we aren't actually doing the padding in the dataset because `__getitem__` does not know about the other items that are being fetched, and therefore does not know what the longest sequence in the batch is. That is all done by the dataloader with the `pad_collate` function you see in the next cell

In [8]:
class QuoteDataset(Dataset):
    """Dataset for Summarizing Benjamin Franklin Quotes"""
    
    def __init__(self, quotes, sources):
        """
        Args:
            quotes (list(string)): A list of quotes
            sources (list(string)): A list of source ids
        """
        self.quotes = quotes
        self.sources = sources
        
        assert len(quotes) == len(sources), "The number of quotes must match the number of sources!"
        
    def __len__(self):
        return len(quotes)
    
    def __getitem__(self, idx):
        if torch.is_tensor(idx):
            idx = idx.tolist()
        
        x_seq = torch.tensor(list(map(lambda char: char_to_ix[char], self.quotes[idx])))
        y = torch.tensor([self.sources[idx]])
            
        return (x_seq, y)
    
dset = QuoteDataset(quotes, sources)
dset[0]

(tensor([18, 13,  3,  3, 20,  6, 17,  7, 13, 20,  4,  5, 20, 22, 13,  9,  9, 13,
         19, 20,  9, 12, 21,  7, 20, 18, 13,  3,  3, 20,  5, 21,  4,  6]),
 tensor([0]))

### Padding Each Batch with the DataLoader
To pad each batch the way we want, we have to write a custom `collate_fn` which is used to combine each item in the batch. It's worth noting that we have to return the length of each input sequence(`x_lens`).

In [9]:
def pad_collate(batch):
    (xx, yy) = zip(*batch)
    x_lens = [len(x) for x in xx]
    xx_pad = pad_sequence(xx, batch_first=True, padding_value=char_to_ix['<pad>'])
    yy = torch.tensor(yy)
    
    return xx_pad, yy, x_lens

dataset = QuoteDataset(quotes, sources)
data_loader = DataLoader(dataset=dataset, batch_size=2, shuffle=True, collate_fn=pad_collate)

### Embedding and DataLoader Testing
A PyTorch embedding is used to convert token ids into a representation vector. These representation vectors are not really human interpretable, but they have some really fascinating qualities that I will not go over here.

Let's make an embedding that represents each word as a 100-dim vector.

Then, lets enumerate through the dataset as we would during training to make sure the shapes all look right. We know the batch size of our dataloader is 2, meaning it fetches two sequences at a time. We also know that our entire dataset only has three sequences. This means our first batch should have two sequences and our second batch should have only one.

In [10]:
embedding = nn.Embedding(nb_char, 100)
for i,(x_padded, y, x_lens) in enumerate(data_loader):
    x_embed = embedding(x_padded)
    print(x_embed.shape)
    print(y)

torch.Size([2, 41, 100])
tensor([2, 1])
torch.Size([1, 34, 100])
tensor([0])


It looks good! As you can see, the first batch returned two sequences(the first number in the shape) each with 41 tokens with each token being represented as a 100-dimension vector.

The second batch has only one sequence with a length of 34.
Now let's see how this would be used in practice.

### Creating an RNN
Let's create an RNN that can handle GPU optimized batching that we showed above. The most important things here to note are the `pack_padded_sequence` here before it is fed into the GRU and `pad_packed_sequence` after it is returned from the GRU. This simply opimizes the sequence representation before it is sent to the GRU.

In [11]:
class RNN(nn.Module):
    def __init__(self):
        super(RNN, self).__init__()
        embedding_dim = 100
        hidden_size = 100
        
        self.embedding = nn.Embedding(nb_char, embedding_dim)
        self.gru = nn.GRU(embedding_dim, hidden_size, batch_first=True)
        self.fc_out = nn.Linear(hidden_size, len(sources))
        
    def forward(self, x, x_lens):
        x_embed = self.embedding(x)
        x_packed = pack_padded_sequence(x_embed, x_lens, batch_first=True, enforce_sorted=False)
        output_packed, hidden = self.gru(x_packed)
        output_padded, output_lengths = pad_packed_sequence(output_packed, batch_first=True)
        output = self.fc_out(output_padded[:, -1, :])
        return output
        

### Training for a Few Batches
Now that we have everything setup, lets train the network for a few batches to show that its working and how easy it is to use the RNN now. This is almost identical to the simplicity of training a CNN

In [12]:
rnn = RNN()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(rnn.parameters(), lr=0.001)
for epoch in range(100):
    for i,(x_padded, y, x_lens) in enumerate(data_loader):
        # This whole section below probably belongs in its own model
        optimizer.zero_grad()
        output = rnn(x_padded, x_lens)
        loss = criterion(output, y)
        loss.backward()
        optimizer.step()

        print(f"Batch Cross Entropy Loss: {loss.item()}")

Batch Cross Entropy Loss: 1.1170361042022705
Batch Cross Entropy Loss: 1.2228976488113403
Batch Cross Entropy Loss: 1.0215411186218262
Batch Cross Entropy Loss: 1.3039233684539795
Batch Cross Entropy Loss: 0.8585443496704102
Batch Cross Entropy Loss: 1.1366260051727295
Batch Cross Entropy Loss: 0.775987982749939
Batch Cross Entropy Loss: 0.9278870820999146
Batch Cross Entropy Loss: 0.8335872888565063
Batch Cross Entropy Loss: 0.39104533195495605
Batch Cross Entropy Loss: 0.7986896634101868
Batch Cross Entropy Loss: 0.32837775349617004
Batch Cross Entropy Loss: 0.6772658824920654
Batch Cross Entropy Loss: 0.4134480059146881
Batch Cross Entropy Loss: 0.7113977670669556
Batch Cross Entropy Loss: 0.20679523050785065
Batch Cross Entropy Loss: 0.6638545989990234
Batch Cross Entropy Loss: 0.1615143120288849
Batch Cross Entropy Loss: 0.6007986664772034
Batch Cross Entropy Loss: 0.1702224612236023
Batch Cross Entropy Loss: 0.5839599370956421
Batch Cross Entropy Loss: 0.12439825385808945
Batch C

Batch Cross Entropy Loss: 0.5068260431289673
Batch Cross Entropy Loss: 0.0026532942429184914
Batch Cross Entropy Loss: 0.523768961429596
Batch Cross Entropy Loss: 0.003945306409150362
Batch Cross Entropy Loss: 0.5234556794166565
Batch Cross Entropy Loss: 0.003855534829199314
Batch Cross Entropy Loss: 0.5230298638343811
Batch Cross Entropy Loss: 0.0037595797330141068
Batch Cross Entropy Loss: 0.5225135684013367
Batch Cross Entropy Loss: 0.0036596960853785276
Batch Cross Entropy Loss: 0.506630003452301
Batch Cross Entropy Loss: 0.002454365836456418
Batch Cross Entropy Loss: 0.5065847635269165
Batch Cross Entropy Loss: 0.002421425189822912
Batch Cross Entropy Loss: 0.521290123462677
Batch Cross Entropy Loss: 0.003401329508051276
Batch Cross Entropy Loss: 0.5062876343727112
Batch Cross Entropy Loss: 0.0024307011626660824
Batch Cross Entropy Loss: 0.5061134099960327
Batch Cross Entropy Loss: 0.002318434417247772


### Conclusion
It all looks good! Thanks for reading!